import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import * as Print from 'expo-print';
import Toast from 'react-native-toast-message';

// Convert markdown to HTML for PDF generation
const markdownToHTML = (markdown, title) => {
  // Basic markdown to HTML conversion
  let html = markdown
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br />')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/^\* (.*$)/gm, '<li>$1</li>')
    .replace(/^\d+\. (.*$)/gm, '<li>$1</li>');

  // Wrap lists in <ul> or <ol>
  html = html.replace(/<li>.*?<\/li>/g, match => {
    if (match.startsWith('<li>1.')) {
      return `<ol>${match}</ol>`;
    }
    return `<ul>${match}</ul>`;
  });

  // Create the full HTML document with styling
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>${title || 'Note'}</title>
        <style>
          body {
            font-family: 'Helvetica', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 20px;
            max-width: 800px;
            margin: 0 auto;
          }
          h1 {
            color: #2c3e50;
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
            margin-top: 30px;
          }
          h2 {
            color: #3498db;
            margin-top: 25px;
          }
          h3 {
            color: #2980b9;
            margin-top: 20px;
          }
          p {
            margin: 15px 0;
          }
          ul, ol {
            margin: 15px 0;
            padding-left: 30px;
          }
          li {
            margin: 5px 0;
          }
          a {
            color: #3498db;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          code {
            background-color: #f8f8f8;
            padding: 2px 5px;
            border-radius: 3px;
            font-family: monospace;
            font-size: 0.9em;
          }
          pre {
            background-color: #f8f8f8;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
          }
          blockquote {
            border-left: 4px solid #ccc;
            padding-left: 15px;
            color: #555;
            margin: 15px 0;
          }
          img {
            max-width: 100%;
            height: auto;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
          }
          .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 0.8em;
            color: #7f8c8d;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title || 'Note'}</h1>
          <p>Generated by 4note</p>
        </div>
        <div class="content">
          <p>${html}</p>
        </div>
        <div class="footer">
          <p>Created with 4note - Your AI-powered note-taking app</p>
        </div>
      </body>
    </html>
  `;
};

// Generate PDF from markdown content
export const exportToPDF = async (markdown, title = 'Note') => {
  try {
    // Convert markdown to HTML
    const html = markdownToHTML(markdown, title);
    
    // Generate PDF file
    const { uri } = await Print.printToFileAsync({ 
      html,
      base64: false
    });
    
    // Create a more user-friendly filename
    const sanitizedTitle = title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 20);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19);
    const fileName = `${sanitizedTitle}_${timestamp}.pdf`;
    
    // On iOS, we can use the Sharing API directly
    if (Platform.OS === 'ios') {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Share ${title}`,
        UTI: 'com.adobe.pdf'
      });
      Toast.show({ text1: 'PDF ready to share' });
      return true;
    }
    
    // On Android, save to downloads folder
    const downloadsDir = FileSystem.documentDirectory + 'Downloads/';
    
    // Create Downloads directory if it doesn't exist
    const dirInfo = await FileSystem.getInfoAsync(downloadsDir);
    if (!dirInfo.exists) {
      await FileSystem.makeDirectoryAsync(downloadsDir, { intermediates: true });
    }
    
    // Copy the file to Downloads directory
    const destinationUri = `${downloadsDir}${fileName}`;
    await FileSystem.copyAsync({
      from: uri,
      to: destinationUri
    });
    
    // Share the file
    await Sharing.shareAsync(destinationUri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share ${title}`,
      UTI: 'com.adobe.pdf'
    });
    
    Toast.show({ text1: 'PDF saved and ready to share' });
    return true;
  } catch (error) {
    console.error('Error exporting PDF:', error);
    Toast.show({ text1: 'Failed to export PDF', text2: error.message, type: 'error' });
    return false;
  }
};
